DELETE http://localhost:3000/post/7
Accept: application/json
Content-Type: application/json

###
POST http://localhost:3000/post
Accept: application/json
Content-Type: application/json

{
  "title": "Premier article",
  "summary": "un texte pour résumer ce faux article",
  "content": "bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla",
  "author": "Laurie",
  "themes": [
    {
      "id": 7
    }
  ]
}

###
PATCH http://localhost:3000/post/5
Accept: application/json
Content-Type: application/json

{
  "themes": [{
    "id": 7
  }]
}

###
POST http://localhost:3000/theme
Accept: application/json
Content-Type: application/json

{
  "title": "Thème 2"
}
