GET http://localhost:3000/post/1
Accept: application/json
Content-Type: application/json

###
POST http://localhost:3000/theme
Accept: application/json
Content-Type: application/json

{
  "title": "Thème 1"
}

###
PATCH http://localhost:3000/post/1
Accept: application/json
Content-Type: application/json

{
  "themes": [{
    "id": 1
  }]
}

###
POST http://localhost:3000/post
Accept: application/json
Content-Type: application/json

{
  "title": "Coucou toi",
  "summary": "bla bla bla",
  "content": "fdsf sdlkfj sdlkfj sdlkfjsdlkfjslkqsd kqsmkqzome ds",
  "themes": [
    {
      "id": 1
    }
  ]
}
